{
  "comments": [
    {
      "key": {
        "uuid": "9abe1de1_c4a243ae",
        "filename": "python-networking-odl.spec",
        "patchSetId": 6
      },
      "lineNbr": 51,
      "author": {
        "id": 403
      },
      "writtenOn": "2018-11-29T09:59:12Z",
      "side": 1,
      "message": "this needs to move to py2/py3 conditional like:-\n\n# Handle python2 exception\n%if %{pyver} \u003d\u003d 2\nRequires:  python-websocket-client\n%else\nRequires:  python%{pyver}-websocket-client\n%endif",
      "range": {
        "startLine": 51,
        "startChar": 0,
        "endLine": 51,
        "endChar": 39
      },
      "revId": "cccb2ac6927c3b794282bc92c16af43d3d0d2191",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9abe1de1_04bb9b28",
        "filename": "python-networking-odl.spec",
        "patchSetId": 6
      },
      "lineNbr": 74,
      "author": {
        "id": 565
      },
      "writtenOn": "2018-11-28T21:43:37Z",
      "side": 1,
      "message": "Since uncommenting this out raised a myriad of flags, I think it should be handled in a separate change - probably by the ODL team so they can ensure the repo is test-ready.",
      "revId": "cccb2ac6927c3b794282bc92c16af43d3d0d2191",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9abe1de1_a4a50fb6",
        "filename": "python-networking-odl.spec",
        "patchSetId": 6
      },
      "lineNbr": 74,
      "author": {
        "id": 403
      },
      "writtenOn": "2018-11-29T09:59:12Z",
      "side": 1,
      "message": "ack for follow up fix.",
      "parentUuid": "9abe1de1_04bb9b28",
      "revId": "cccb2ac6927c3b794282bc92c16af43d3d0d2191",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    }
  ]
}